apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image:1.1  # Local image name
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: PORT
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: MONGO_URI
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP  
