apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: bW9uZ29fdXNlcg==       # base64 for 'mongo_user'
  password: bW9uZ29fcGFzc3dvcmQ=   # base64 for 'mongo_password'
